infinispan:
  #Build configuration
  images:
    server: quay.io/infinispan/server:latest
    initContainer: quay.io/app-sre/ubi8-ubi-minimal
  #Deployment configuration
  deploy:
    nameOverride: infinispan-server
    #Add a user with full security authorization.
    security:
      batch: "user create admin -p changeme"
    #Create a cluster with two pods.
    replicas: 2

wildfly:
  build:
    uri: https://github.com/tommaso-borgato/openshift-jee-sample.git
    ref: jakartaee
    s2i:
      version: latest
      builderImage: quay.io/wildfly/wildfly-s2i-jdk17
      runtimeImage: quay.io/wildfly/wildfly-runtime-jdk17
  deploy:
    replicas: 1
    env:
      - name: MAVEN_ARGS_APPEND
        value: "-Dserver-feature-pack.location=org.wildfly:wildfly-galleon-pack:27.0.0.Alpha4 -Dcloud-feature-pack.location=org.wildfly.cloud:wildfly-cloud-galleon-pack:2.0.0.Alpha4"
